export const recieverConstants = {
    GET_RECIEVER_SUCCESS: 'GET_RECIEVER_SUCCESS',
    GET_RECIEVER_FAILURE: 'GET_RECIEVER_FAILURE',

    CREATE_RECIEVER_SUCCESS: 'CREATE_RECIEVER_SUCCESS',
    CREATE_RECIEVER_FAILURE: 'CREATE_RECIEVER_FAILURE',
}